name: egm722_assessment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - geopandas
  - cartopy>=0.21
  - notebook=6.5.3
  - rasterio
  - pyepsg
  - folium
  - numpy
  - rasterstats>=0.18